#!/usr/bin/env ansible-playbook
---
- name: Manage Kubernetes cluster
  hosts: all:!localhost:!bastion
  become: true
  gather_facts: false

  pre_tasks:

    - name: Set hostname from Ansible inventory
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"

# https://kubespray.io/#/
- name: Install Kubernetes
  ansible.builtin.import_playbook: kubernetes_sigs.kubespray.cluster

# To run k9s and playbooks on controller host
- name: Copy .kube/config
  ansible.builtin.import_playbook: kube-config.yml
