#!/usr/bin/env ansible-playbook
---
- name: Install kbcli
  hosts: controller
  become: true
  tags: [kbcli]

  pre_tasks:
    - name: Log desired_state
      ansible.builtin.debug:
        msg: "{{ desired_state }}"

  tasks:
    - name: Configure KubeBlocks
      when: (desired_state is not defined) or (desired_state == 'present')
      ansible.builtin.include_role:
        name: clusterlust.kbcli

- name: Manage KubeBlocks
  hosts: localhost
  become: false
  connection: local
  vars:
    # Semaphore does not pass $HOME so K8S_AUTH_KUBECONFIG needs to be set.
    k8s_auth_kubeconfig: /home/semaphore/.kube/config

  pre_tasks:
    - name: Log desired_state
      ansible.builtin.debug:
        msg: "{{ desired_state }}"

  tasks:
    - name: Configure KubeBlocks
      ansible.builtin.include_role:
        name: clusterlust.kubeblocks

- name: Remove kbcli
  hosts: controller
  become: true
  tags: [kbcli]
  tasks:
    - name: Remove kbcli
      when: (desired_state is defined) and (desired_state == 'absent')
      ansible.builtin.include_role:
        name: clusterlust.kbcli
